package gem

const (
	_doNotEditFolderFilename = "DO_NOT_EDIT_THIS_FOLDER!!!.md"
	_doNotEditFolderContent  = `# DO NOT EDIT THIS FOLDER!!!
This migration folder is generated by [gem](https://github.com/yanun0323/gem), please check the [documentation](https://github.com/yanun0323/gem).`
)
